#!/usr/bin/env python3
"""How far does the ICD join key we already hold actually reach?

    python3 icd_coverage.py    # print the numbers, write icd-coverage.md

OFFLINE. Everything it needs is already in `mondo-terms.json`, which
`mondo_sync.py` fetched, annotated with the purpose of each cross-reference
source — *"ICD10WHO: burden — the route into GBD cause mappings"* — committed,
and which nothing has read since.

WHY ASK BEFORE BUILDING. The register's largest unsourced block is `burden`:
205 scalars in the `sourceable` tier, every one of them a deaths, cases or
prevalence figure that a national statistics office publishes and this register
carries as `src: recall`. **The join key to that data is an ICD code**, and the
question is not whether ICD is useful but whether the mapping we already have is
good enough to build on.

THE FLAVOURS ARE NOT INTERCHANGEABLE AND THAT IS THE POINT OF THIS REPORT.

  ICD10WHO          the international mortality standard. **This is the one that
                    joins to the WHO Mortality Database**, which is free, national,
                    and decades deep. It is the only flavour that answers the
                    question the register actually has.
  ICD10CM           the United States clinical modification. Billing and
                    morbidity, one country. Not a mortality key.
  icd11.foundation  an entity id in ICD-11's foundation layer, NOT a code. The
                    codes used for mortality live in the MMS linearization, and
                    getting from one to the other needs a second lookup.
  ICD9              historical. Still the key for series before roughly 1999.
  ICDO              oncology morphology, a different axis entirely.

So "89 of 100 records have an ICD cross-reference" is true and nearly useless.
The number that decides whether this is worth building is how many records that
**carry a deaths figure** also carry an **ICD10WHO** code.
"""

from __future__ import annotations

import glob
import json
import os
from collections import Counter

import check

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT = os.path.join(HERE, "mondo-terms.json")
REPORT = os.path.join(HERE, "icd-coverage.md")

# In descending order of usefulness for the register's actual problem.
FLAVOURS = ["ICD10WHO", "icd11.foundation", "ICD10CM", "ICD9", "ICDO"]

# Records where ICD's boundary is predicted to disagree with the register's,
# from the "six kinds of zero" (gaps.md #182, #211). Listed here so the report
# checks a prediction rather than describing whatever it finds.
PREDICTED_MISMATCH = {
    "heart-failure": "GBD models it as an impairment; ICD's cause hierarchy is exclusive",
    "anaemia": "same — an impairment, and a record composed of other records",
    "osteoporosis": "hip fracture deaths code to the external cause (falls)",
    "mesothelioma": "asbestos lung cancer is indistinguishable from any other",
    "head-neck-cancer": "four subsites the register holds as one entity",
    "neonatal-conditions": "most of an ICD chapter held as one record",
    "prion-disease": "sporadic, genetic and acquired forms coded separately",
    "als": "short illness — prevalence and mortality behave differently",
}


def load():
    with open(SNAPSHOT, encoding="utf-8") as fh:
        terms = json.load(fh)["terms"]
    recs = [check.load(p) for p in
            sorted(glob.glob(os.path.join(HERE, "entities", "*.yaml")))]
    return terms, [r for r in recs if check.status(r) == "active"]


def row(rec, terms):
    mid = rec.get("mondo", "unresolved")
    x = (terms.get(mid) or {}).get("xrefs") or {}
    deaths = (rec["burden"].get("deaths") or {}).get("value")
    return {
        "slug": rec["slug"],
        "mondo": mid,
        "in_snapshot": mid in terms,
        "has_deaths": bool(deaths),
        "codes": {f: x.get(f, []) for f in FLAVOURS},
    }


def main() -> int:
    terms, recs = load()
    rows = [row(r, terms) for r in recs]

    have = lambda f, rs=None: [r for r in (rs or rows) if r["codes"][f]]
    with_deaths = [r for r in rows if r["has_deaths"]]

    lines = [
        "# ICD coverage — what the join key we already hold actually reaches",
        "",
        "GENERATED by `python3 icd_coverage.py`, offline, from `mondo-terms.json`.",
        "**Nothing here was fetched; `mondo_sync.py` had already stored all of it.**",
        "",
        "## The question",
        "",
        "The register's largest unsourced block is `burden` — 205 scalars in the",
        "`sourceable` tier, every one a figure some statistics office publishes and",
        "this register carries as `src: recall`. **The join key to that data is an",
        "ICD code.** This asks whether the mapping already in hand is good enough to",
        "build on, before anything gets built.",
        "",
        "## Coverage, by flavour",
        "",
        "| flavour | what it is for | records | of those, records with a deaths figure |",
        "|---|---|---:|---:|",
    ]
    purpose = {
        "ICD10WHO": "**international mortality standard — the one that matters**",
        "icd11.foundation": "an entity id, *not* a code — needs MMS linearization",
        "ICD10CM": "US clinical modification; billing, one country",
        "ICD9": "historical series before ~1999",
        "ICDO": "oncology morphology, different axis",
    }
    for f in FLAVOURS:
        lines.append(f"| `{f}` | {purpose[f]} | {len(have(f))} | "
                     f"{len(have(f, with_deaths))} |")

    none_at_all = [r for r in rows if not any(r["codes"].values())]
    lines += [
        f"| *(no ICD xref of any kind)* | — | {len(none_at_all)} | "
        f"{len([r for r in none_at_all if r['has_deaths']])} |",
        "",
        f"**{len(rows)} active records · {len(with_deaths)} carry a deaths figure.**",
        "",
    ]

    # ---- the number that decides it -------------------------------------
    key = have("ICD10WHO", with_deaths)
    lines += [
        "## The number that decides whether to build this",
        "",
        f"**{len(key)} of {len(with_deaths)} records that carry a deaths figure have an",
        f"`ICD10WHO` code** — the only flavour here that joins to the WHO Mortality",
        "Database.",
        "",
        "Everything else is a second lookup away at best. `icd11.foundation` ids are",
        "foundation entities rather than codes; the mortality codes live in the MMS",
        "linearization and getting from one to the other is another API and another",
        "mapping decision. `ICD10CM` is one country's billing modification.",
        "",
    ]

    # ---- cardinality ----------------------------------------------------
    multi = [(r["slug"], r["codes"]["ICD10WHO"]) for r in rows
             if len(r["codes"]["ICD10WHO"]) > 1]
    lines += [
        "## Cardinality — a prediction the data did NOT support",
        "",
        "Before running this it was asserted that the mapping is many-to-many, so an",
        f"`icd:` field would have to be a list. **It is {len(multi)} of "
        f"{len(have('ICD10WHO'))}** — every single",
        "`ICD10WHO` cross-reference MONDO carries is one code.",
        "",
        "That is not evidence the real mapping is 1:1. It is evidence **MONDO records",
        "only exact matches**, which is the same property that makes `also` untrustworthy",
        "for auto-accept (mondo-sync.md). The many-to-many-ness is filtered out upstream,",
        "not absent. The list-and-never-auto-accept rule still holds; what does not hold",
        "is the claim that this data shows it.",
        "",
    ]
    for slug, codes in sorted(multi)[:12]:
        lines.append(f"- **{slug}** → {', '.join(codes)}")
    if multi:
        lines.append("")

    # ---- the full census: what IS the bridge? ---------------------------
    census = Counter()
    census_d = Counter()
    for rec in recs:
        x = (terms.get(rec.get("mondo"), {}) or {}).get("xrefs") or {}
        got = {r["slug"]: r for r in with_deaths}
        for k in x:
            census[k] += 1
            if rec["slug"] in got:
                census_d[k] += 1
    lines += [
        "## The full cross-reference census — where the bridge actually is",
        "",
        "This is the table that decides it, and it is not about ICD at all.",
        "",
        "| source | records | with a deaths figure |",
        "|---|---:|---:|",
    ]
    for k, n in census.most_common():
        mark = "**" if k in ("UMLS", "ICD10WHO") else ""
        lines.append(f"| {mark}`{k}`{mark} | {n} | {census_d[k]} |")
    lines += [
        "",
        f"**`UMLS` reaches {census['UMLS']} of {len(rows)} records and "
        f"{census_d['UMLS']} of {len(with_deaths)} of the ones with deaths** — against",
        f"`ICD10WHO`'s {census['ICD10WHO']} and {census_d['ICD10WHO']}. UMLS is a *crosswalk*: its whole",
        "job is holding one concept's identifiers across vocabularies, ICD-10 and",
        "ICD-10-CM included. So the route to an ICD code is **MONDO → UMLS → ICD**, and",
        "the direct MONDO → ICD edge this report set out to measure is the wrong edge.",
        "",
        "Note also that `ICD9` (74) beats `ICD10WHO` (27) nearly three to one. A",
        "vocabulary retired from mortality coding around 1999 has the better coverage,",
        "because those xrefs arrived through legacy DOID and OMIM merges. **Coverage here",
        "reflects MONDO's merge history, not the usefulness of the code.**",
        "",
    ]

    # ---- the prediction -------------------------------------------------
    lines += [
        "## The predicted mismatches, checked",
        "",
        "gaps.md #182 and #211 catalogue six kinds of zero in the `deaths` column, and",
        "**five of the six are artefacts of how ICD assigns an underlying cause.** These",
        "records were listed in the script *before* running it, so this table checks a",
        "prediction rather than describing whatever turned up.",
        "",
        "| record | deaths | ICD10WHO | why the boundary is expected to disagree |",
        "|---|---:|---|---|",
    ]
    by_slug = {r["slug"]: r for r in rows}
    for slug, why in sorted(PREDICTED_MISMATCH.items()):
        r = by_slug.get(slug)
        if not r:
            continue
        codes = ", ".join(r["codes"]["ICD10WHO"]) or "—"
        d = "yes" if r["has_deaths"] else "**0**"
        lines.append(f"| `{slug}` | {d} | {codes} | {why} |")
    lines.append("")

    # ---- what is missing ------------------------------------------------
    gap = [r for r in with_deaths if not r["codes"]["ICD10WHO"]]
    lines += [
        "## Records with deaths and no mortality key",
        "",
        f"**{len(gap)} records carry a deaths figure and have no `ICD10WHO` code.**",
        "These are the ones a burden-sourcing pass could not start on today.",
        "",
    ]
    lines += [
        "**They are not a random 58.** `stroke` and `colorectal-cancer` carry no ICD",
        "code of any flavour while carrying SNOMED, UMLS, MeSH, NCIt and DOID — so this",
        "is MONDO's ICD coverage being patchy, not our identifier being odd. The two of",
        "them are among the largest killers in the register. **Coverage is worst where",
        "burden is highest**, which is the opposite of what a sourcing pass needs.",
        "",
    ]
    for r in sorted(gap, key=lambda r: r["slug"]):
        other = [f for f in FLAVOURS if f != "ICD10WHO" and r["codes"][f]]
        lines.append(f"- `{r['slug']}` — "
                     + (f"has {', '.join(other)}" if other else "**no ICD xref at all**"))
    lines.append("")

    with open(REPORT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"{len(rows)} records · {len(with_deaths)} with deaths")
    for f in FLAVOURS:
        print(f"  {f:<18}{len(have(f)):>4} records · "
              f"{len(have(f, with_deaths)):>4} of those have deaths")
    print(f"  {'(none)':<18}{len(none_at_all):>4} records")
    print(f"\nDECIDING NUMBER: {len(key)} of {len(with_deaths)} records with a deaths "
          f"figure have an ICD10WHO code")
    print(f"wrote {os.path.relpath(REPORT, HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
