/* =====================================================================
 * Nordstern dashboard tests — run with:  node --test web/
 *
 * THE RULE THIS FILE ENFORCES, AND IT IS THE ONLY REASON IT EXISTS:
 *
 *   **Every figure on the dashboard links to the query that produces it, and
 *   that query must actually return that number.**
 *
 * A statistic you cannot express as a query is one nobody can check. Worse, a
 * statistic whose query returns something *else* is a page telling a visitor
 * one thing and the tool telling them another — and the visitor will believe
 * the page, because it is the one with the big number on it.
 *
 * So this file renders the real dashboard against the real generated
 * artifacts, pulls every `query.html?q=…` link out of the result along with the
 * figure printed beside it, runs each query through the real query engine, and
 * compares. It is the same discipline as the two `index.md` guards in
 * test_check.py: recompute rather than trust.
 *
 * It also pins the second rule — that the page owns no derivation. Every number
 * must come from `snapshots.js` or `slim.js`, both generated by check.py.
 * ===================================================================== */
const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const DIR = __dirname;
const Query = require("./query.js");

/* ---- render the real page in a fake DOM ----------------------------- */
function boot() {
  const html = fs.readFileSync(path.join(DIR, "index.html"), "utf8");
  const inline = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
  assert.equal(inline.length, 1, "expected exactly one inline <script>");

  const els = {};
  const get = id => (els[id] ||= { id, innerHTML: "" });
  ["prov", "body", "series"].forEach(get);

  const sandbox = {
    window: {},
    document: { getElementById: get },
    location: { href: "" },
    encodeURIComponent, decodeURIComponent,
    JSON, Object, Array, Set, Map, String, Number, Math, RegExp, console,
  };
  sandbox.window = sandbox;

  for (const f of ["banner.js", "slim.js", "snapshots.js", "engpass-snapshots.js"])
    vm.runInContext(fs.readFileSync(path.join(DIR, f), "utf8"), vm.createContext(sandbox));
  vm.runInContext(inline[0][1], sandbox, { filename: "index.html:inline" });

  const rendered = els.prov.innerHTML + els.body.innerHTML + els.series.innerHTML;
  return { html, rendered, sandbox,
           snap: sandbox.window.NORDSTERN_SNAPSHOTS.at(-1),
           esnap: sandbox.window.ENGPASS_SNAPSHOTS.at(-1),
           slim: sandbox.window.NORDSTERN_SLIM };
}

/* Pull every query link out of the rendered markup. */
function links(rendered) {
  return [...rendered.matchAll(/query\.html\?q=([^"'#]+)/g)]
    .map(m => decodeURIComponent(m[1]));
}

/* data.js assigns to `window` at top level, so it cannot be require()d —
   it has to run inside a context that has one. Same trick as tool.test.js. */
function loadRecords() {
  const s = { window: {}, JSON, Object, Array, console };
  s.window = s;
  vm.createContext(s);
  vm.runInContext(fs.readFileSync(path.join(DIR, "data.js"), "utf8"), s);
  return s.window.NORDSTERN.records;
}

/* ---- the page renders at all ---------------------------------------- */

test("dashboard renders from the generated artifacts", () => {
  const { rendered, snap, slim } = boot();
  assert.ok(rendered.length > 4000, "page rendered almost nothing");
  assert.ok(!/undefined|NaN|\[object Object\]/.test(rendered),
            "rendered output contains undefined/NaN — a field name is wrong");
  assert.equal(slim.length, snap.records.active,
               "slim.js and the snapshot disagree about how many records there are");
});

test("the banner warns in one sentence and keeps its ledger", () => {
  const { sandbox, snap } = boot();
  const prov = sandbox.document.getElementById("prov").innerHTML;
  assert.ok(prov.length > 200, "the provenance banner is empty");

  /* THE VISIBLE PART IS THE WARNING; THE NUMBERS ARE ONE CLICK BELOW IT.
     The first version said everything at full length above everything else. It
     was accurate and unreadable — a warning long enough to skip is a warning
     that does not warn. This asserts the short form stayed short AND that
     shortening it did not quietly delete the evidence, which would leave a
     vague disclaimer nobody can check. */
  const visible = prov.split("<details")[0].replace(/<[^>]+>/g, " ")
                      .replace(/\s+/g, " ").trim();
  assert.match(visible, /experimental dataset/i,
               "the one thing a visitor must carry away is that this is experimental");
  assert.match(visible, /not everything here is verified or sourced/i);
  assert.ok(visible.length < 220,
            `the visible warning is ${visible.length} chars — it must stay one sentence`);
  assert.match(prov, /<details/, "the ledger must survive the shortening, collapsed");
  // The banner leads with the SOURCEABLE tier, not the raw total — see
  // check.py's `by_tier`. It used to lead with "0 of 1,582".
  const t = snap.provenance.by_tier;
  assert.match(prov, new RegExp(`${t.sourceable.cited} of ${t.sourceable.total.toLocaleString("en-US")}`),
               "banner must state the sourceable count, whatever it is");
  if (t.supportable.cited)
    assert.ok(prov.includes(String(t.supportable.cited)),
              "citations that exist must be reported, not buried — the banner " +
              "should not understate the register any more than it overstates it");
  assert.ok(/recall/.test(prov) && /reasoning/.test(prov) && /unknown/.test(prov),
            "the banner must name all three unsourced kinds, including `unknown`");
});

/* ---- THE RULE ------------------------------------------------------- */

test("every query the dashboard links to parses without error", () => {
  const { rendered } = boot();
  const recs = loadRecords();
  const qs = links(rendered);
  assert.ok(qs.length >= 25, `only ${qs.length} query links found — expected many more`);
  const bad = [];
  for (const q of qs) {
    const res = Query.run(recs, q);
    if (res.errors && res.errors.length) bad.push(`${q} → ${JSON.stringify(res.errors)}`);
  }
  assert.deepEqual(bad, [], "dashboard links to queries the engine rejects:\n" + bad.join("\n"));
});

test("no dashboard query returns an empty set", () => {
  const { rendered } = boot();
  const recs = loadRecords();
  const empty = links(rendered).filter(q => Query.run(recs, q).records.length === 0);
  assert.deepEqual(empty, [],
    "a figure links to a query that matches nothing — either the figure is " +
    "wrong or the field name is:\n" + empty.join("\n"));
});

/* The load-bearing one. A figure and its link must agree.
 *
 * Only checked for links whose printed figure is a plain count of records —
 * a `stat()` card or a bar row. Ratios, medians and per-blocker counts are
 * exercised by the two tests above and by the snapshot tests in test_check.py,
 * because the query engine counts RECORDS and those numbers do not. */
test("every record-count figure matches what its query returns", () => {
  const { rendered } = boot();
  const recs = loadRecords();

  // stat cards carrying data-count="records" — the marker `stat()` adds only
  // when a query was supplied
  const cards = [...rendered.matchAll(
    /<a class="q" href="query\.html\?q=([^"]+)"><div class="card">\s*<div class="stat[^"]*" data-count="records">([^<]+)<\/div>/g)];
  // bar rows likewise. A row marked data-count="items" is counting blockers or
  // mentions, and the query — which counts records — correctly returns a
  // different number. That distinction is the reason this test exists.
  const rows = [...rendered.matchAll(
    /href="query\.html\?q=([^"]+)"[^>]*>[^<]*<\/a>\s*<\/td>\s*<td class="num" data-count="records">([\d,]+)<\/td>/g)];

  assert.ok(cards.length >= 6, `found only ${cards.length} record-count stat cards`);
  assert.ok(rows.length >= 20, `found only ${rows.length} record-count bar rows`);

  const mismatches = [];
  for (const [, rawQ, rawN] of [...cards, ...rows]) {
    const q = decodeURIComponent(rawQ);
    const shown = rawN.replace(/,/g, "").trim();
    if (!/^\d+$/.test(shown)) continue;      // ratios, percentages, medians
    const got = Query.run(recs, q).records.length;
    if (got !== Number(shown))
      mismatches.push(`"${q}" shows ${shown}, returns ${got}`);
  }
  assert.deepEqual(mismatches, [],
    "a figure disagrees with its own query:\n  " + mismatches.join("\n  "));
});

/* ---- the page owns no derivation ------------------------------------ */

test("the dashboard computes no derivation of its own", () => {
  const { html } = boot();
  const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
  // The derivation names check.py owns. Seeing one on the left of an `=` here
  // would mean the page decided it, and the two implementations would drift.
  for (const name of ["capability", "quadrant", "delivery", "reach", "terms",
                      "orphaned", "measurement_gap"]) {
    const assigned = new RegExp(`(function|const|let|var)\\s+${name}\\s*[=(]`);
    assert.ok(!assigned.test(script),
      `dashboard defines its own ${name}() — check.py owns that derivation`);
  }
});

test("the dashboard reads slim.js, not the 2 MB payload", () => {
  const { html } = boot();
  assert.ok(/src="slim\.js"/.test(html), "should load slim.js");
  assert.ok(!/src="data\.js"/.test(html),
            "the landing page must not pull the full register — it is the casual page");
});

test("the snapshot series status is honest about how many bearings exist", () => {
  const { sandbox } = boot();
  const n = sandbox.window.NORDSTERN_SNAPSHOTS.length;
  const series = sandbox.document.getElementById("series").innerHTML
                        .replace(/\s+/g, " ");
  if (n === 1)
    assert.match(series, /cannot say anything about progress/,
      "with one snapshot the page must say the comparison does not exist yet");
  else
    assert.match(series, new RegExp(`${n} bearings`));
});

/* ---- routing --------------------------------------------------------
 * The two pages are one idea split by audience: `index.html` is the map a
 * casual visitor lands on, `query.html` is the tool somebody goes to on
 * purpose. They were swapped on 2026-08-26, which meant touching every `?q=`
 * link, two test harnesses and the docs — the kind of change that leaves one
 * dangling reference behind and nobody notices until a link 404s in public.
 * ------------------------------------------------------------------- */

test("the landing page is the dashboard and the tool is query.html", () => {
  const idx = fs.readFileSync(path.join(DIR, "index.html"), "utf8");
  const qry = fs.readFileSync(path.join(DIR, "query.html"), "utf8");

  assert.ok(/window\.NORDSTERN_SNAPSHOTS/.test(idx),
            "index.html should be the dashboard — it reads the snapshot series");
  assert.ok(/NordsternQuery|window\.NORDSTERN\b/.test(qry),
            "query.html should be the query tool");
  // The dashboard must not have become the heavy page by accident.
  assert.ok(!/src="data\.js"/.test(idx),
            "index.html pulls the 2 MB payload — the landing page reads slim.js");
});

test("the two pages link to each other, and to nothing that has moved", () => {
  const idx = fs.readFileSync(path.join(DIR, "index.html"), "utf8");
  const qry = fs.readFileSync(path.join(DIR, "query.html"), "utf8");

  assert.match(idx, /href="query\.html"/, "the map must offer the tool");
  assert.match(qry, /href="index\.html"/, "the tool must offer a way back to the map");

  // `dashboard.html` was the dashboard's address for exactly one day. Any
  // surviving reference to it is a dead link.
  for (const [name, src] of [["index.html", idx], ["query.html", qry]])
    assert.ok(!/dashboard\.html/.test(src),
              `${name} still references dashboard.html, which no longer exists`);

  // And the dashboard must send figures to the tool, not to itself.
  assert.ok(!/"index\.html\?q=/.test(idx),
            "a dashboard figure links to index.html?q= — the query tool is query.html");
});

/* ---- the burden-weighted figure ------------------------------------- */

/* This section makes a CLAIM — that the biggest knowledge gaps are in the
 * common diseases, not the rare terrible ones — and a reader will take the
 * chart as evidence for it. So the claim is asserted here against the real
 * artifacts. If a re-rating overturns it, this fails and the prose gets
 * rewritten, rather than the page going quietly on saying something untrue. */
test("the burden-weighted figure states its exclusions and its claim holds", () => {
  const { rendered, snap, slim } = boot();
  const text = rendered.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");

  // It must say how many records it cannot see. A chart that silently drops a
  // sixth of the register reads as though it covered everything.
  const missing = snap.records.active - snap.gaps.rated;
  assert.ok(missing > 0, "expected some records to be unrateable");
  assert.match(text, new RegExp(`${missing} records are missing from the chart`),
               "the figure must state how many records it excludes");
  assert.match(text, /Rabies is the case that forces that exclusion/,
               "the exclusion must name the record that forces it, not just the rule");
  assert.match(text, /construct, not a measurement/,
               "the proxy caveat must survive — efficacy is not a mortality reduction");

  // The claim itself.
  const rated = slim.filter(r => r.knowledge_gap != null);
  const top = rated.reduce((a, b) => (b.knowledge_gap > a.knowledge_gap ? b : a));
  const helpless = slim.filter(r => r.efficacy === 0)
                       .reduce((s, r) => s + (r.deaths || 0), 0);
  assert.ok(top.knowledge_gap > 10 * helpless,
    `the section claims the common diseases hold the bigger gaps: ${top.slug} is ` +
    `${top.knowledge_gap} against ${helpless} total deaths where nothing works`);

  // Every dot on the chart is a record the register can actually rate.
  assert.equal(rated.length, snap.gaps.rated,
               "slim.js and the snapshot disagree about how many records carry a gap");
});

test("the two gaps partition the burden, in the snapshot as in the records", () => {
  const { snap, slim } = boot();
  const k = slim.reduce((s, r) => s + (r.knowledge_gap || 0), 0);
  const d = slim.reduce((s, r) => s + (r.delivery_gap || 0), 0);
  assert.ok(Math.abs(k - snap.gaps.knowledge) < 1, "slim and snapshot disagree on knowledge");
  assert.ok(Math.abs(d - snap.gaps.delivery) < 1, "slim and snapshot disagree on delivery");
  for (const r of slim.filter(x => x.knowledge_gap != null))
    assert.ok(r.knowledge_gap + r.delivery_gap <= r.deaths + 1e-6,
              `${r.slug}: the gaps exceed the burden they partition`);
});

/* ---- the standfirst ------------------------------------------------- */

/* The page is ten charts and a visitor will reasonably assume they add up to a
 * verdict. They do not, and the register has been forced to that conclusion six
 * separate times — efficacy vs access, survival vs outcome, `gain` computed and
 * never sorted on, `strata` flagged malformed-not-hard, `preventable` added
 * rather than folded in, and the burden gaps being mortality-shaped. Every one
 * of those refusals is documented per field; NONE of them was stated about the
 * page as a whole until this paragraph. It is load-bearing framing, not decoration. */
test("the map states that there is no single score, and counts its own readings", () => {
  const { rendered } = boot();
  const text = rendered.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");

  assert.match(text, /There is no single score here, and there will not be one/,
               "the standfirst is the page's own framing — it must not be dropped");
  assert.match(text, /Those are all true at once/,
               "the three standpoints must be given as simultaneously valid");

  // The claim "N readings" must equal the sections actually on the page. A
  // hardcoded number would be wrong the first time a section was added, on the
  // one paragraph whose whole point is honesty about what the page is.
  const sections = (rendered.match(/<span class="n">/g) || []).length;
  assert.match(text, new RegExp(`this page is ${sections} readings`),
               `the standfirst must agree with the ${sections} sections rendered`);
  assert.ok(!/\{\{sections\}\}/.test(rendered), "the placeholder was not substituted");
});

/* ---- the buckets ----------------------------------------------------- */

test("axis A is drawn as a partition and axis B is not", () => {
  const { rendered, snap } = boot();
  const text = rendered.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");
  const B = snap.buckets;

  // A stacked bar is only honest about a partition. If axis A ever stopped
  // summing to the register, the widths would stop being shares.
  const total = Object.values(B.a).reduce((a, b) => a + b, 0);
  assert.equal(total, snap.records.active, "axis A must cover every active record");

  // And the page must say, in words, that B is not one — a reader who adds the
  // tag column up gets a number larger than the register.
  assert.match(text, /These are tags, not a partition — do not add them up/,
               "axis B must warn against being summed");
  const tagTotal = Object.values(B.b).reduce((a, b) => a + b, 0);
  assert.ok(tagTotal > snap.records.active,
            "tags should over-count the register — that is why the warning exists");

  // The version machinery has to be visible, or nobody knows the counts are
  // only comparable within a version.
  assert.match(text, new RegExp(`buckets\\.yaml at version ${B.version}`),
               "the page must state which version of the definitions it drew");
});

test("the bucket labels come from buckets.yaml, not from the page", () => {
  const { html, snap } = boot();
  const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
  assert.ok(snap.buckets.names && Object.keys(snap.buckets.names).length >= 12,
            "the snapshot must carry the display names");
  // A second copy of a label in the HTML is the drift that already bit the
  // provenance banner once — three hand-written copies, one of them years stale.
  for (const name of Object.values(snap.buckets.names))
    assert.ok(!script.includes(`"${name}"`),
              `"${name}" is hardcoded in index.html — it belongs to buckets.yaml`);
});

test("the headline bucket claim is true of the data", () => {
  const { snap } = boot();
  const A = snap.buckets.a;
  /* THE THRESHOLD USED TO BE AN ARBITRARY 5x AND buckets.yaml v3 BROKE IT.
     Keying `changes-you` on residue severity rather than presence moved eight
     records into `back-to-normal`, which went from 6 to 14 while `changes-you`
     fell from 67 to 60 — so the ratio dropped below five and the test failed on
     a claim that had not actually stopped being true.
     A test should assert the claim the page makes, not a number that happened
     to hold when it was written. The page says `changes-you` is the LARGEST
     state in the register and that it dwarfs simple recovery; both are checked
     directly. */
  const largest = Object.entries(A).sort((a, b) => b[1] - a[1])[0][0];
  assert.equal(largest, "changes-you",
    "the section claims survival-in-an-altered-body is the characteristic " +
    `output of medicine, so it must be the largest bucket; largest is ${largest}`);
  assert.ok(A["changes-you"] > (A["back-to-normal"] || 0) * 2,
    `changes-you=${A["changes-you"]} must clearly exceed ` +
    `back-to-normal=${A["back-to-normal"]} for the comparison in the prose to hold`);
  /* AND THE SAME LESSON AGAIN, ONE LINE LATER. This used to assert
     `ends-it + ends-it-unless-caught < 5`, which is another number that happened
     to hold when it was written — it broke on 2026-09-02 when three records were
     added to `ends-it` precisely because that bucket held one entry and nobody
     believed it. The page's claim is that the category everyone pictures is the
     SMALLEST, so assert that and let the counts do what they do. */
  const order = Object.entries(A).sort((a, b) => a[1] - b[1]).map(x => x[0]);
  assert.deepEqual(order.slice(0, 2).sort(), ["ends-it", "ends-it-unless-caught"],
    "the section calls the terminal categories the smallest in the register; " +
    `ascending order is ${order.join(" < ")}`);
});

/* =====================================================================
 * THE BUCKET SPINE — added 2026-09-02, when the page was rebuilt so that the
 * seven states lead and each one lists what is in it.
 *
 * A count is an assertion and a list of names is a thing you can argue with, so
 * the sections print the membership. That makes a new way to be wrong available:
 * a section whose heading says 63 and whose chip field holds 61. These tests
 * close it the same way the rest of the file does — recompute, do not trust.
 * ===================================================================== */

/* Arrays out of the vm context carry that realm's Array.prototype, and
   deepStrictEqual compares prototypes — spreading rebuilds them here. */
const here = xs => [...(xs || [])];

/* Chips display the record's human NAME — "Uncorrected refractive error", not
   `refractive-error` — so the identity a test compares on is carried in an
   explicit `data-slug` rather than scraped out of display text. The display
   text is for people and is allowed to change. */
const chipSlugs = html =>
  [...html.matchAll(/<a class="chip" data-slug="([a-z0-9-]+)"/g)].map(m => m[1]);

/* The markup between one <h2> and the next. Both axes render section bodies
   the same way, so one helper serves the seven states and the six tags. */
function sectionBody(rendered, heading) {
  const start = rendered.indexOf(`</span>${heading}</h2>`);
  assert.ok(start > -1, `no section headed ${heading}`);
  const rest = rendered.slice(start);
  const end = rest.indexOf("<h2>", 1);
  return end > -1 ? rest.slice(0, end) : rest;
}

const BUCKET_ORDER = ["ends-it", "ends-it-unless-caught", "ends-it-later",
                      "held-off", "defines-your-life", "changes-you",
                      "back-to-normal"];

test("every bucket has its own section, in the order the strip is drawn in", () => {
  const { rendered, snap } = boot();
  const heads = [...rendered.matchAll(/<h2><span class="n">(\d\d)<\/span>([^<]+)<\/h2>/g)]
    .map(m => [m[1], m[2].trim()]);
  const names = BUCKET_ORDER.map(k => snap.buckets.names[k]);
  const got = heads.filter(([, t]) => names.includes(t)).map(([, t]) => t);
  assert.deepEqual(got, names,
    "the seven bucket sections must appear once each, in strip order");
});

test("each bucket section lists exactly the records the snapshot puts in it", () => {
  const { rendered, snap, slim } = boot();
  // Sections are delimited by their own headings; take the slice for each.
  for (const k of BUCKET_ORDER) {
    const head = snap.buckets.names[k];
    const start = rendered.indexOf(`>${head}</h2>`);
    assert.ok(start > -1, `no section for ${k}`);
    const rest = rendered.slice(start);
    const end = rest.indexOf("<h2>", 1);
    const body = end > -1 ? rest.slice(0, end) : rest;

    const chips = chipSlugs(body);
    const expect = Object.entries(snap.buckets.members)
      .filter(([, v]) => v.a === k).map(([s]) => s).sort();
    assert.deepEqual(chips.slice().sort(), expect,
      `${k}: the chip field disagrees with the snapshot's membership`);
    assert.equal(chips.length, snap.buckets.a[k],
      `${k}: the heading count and the number of names printed disagree`);
    // and slim.js, which is what the chips are actually rendered from
    assert.equal(slim.filter(r => r.bucket === k).length, snap.buckets.a[k],
      `${k}: slim.js and the snapshot disagree about how many are in this bucket`);
  }
});

test("the seven sections together are a partition — every record exactly once", () => {
  /* SCOPED TO THE AXIS-A SECTIONS, and the scoping is the point rather than
     bookkeeping. When axis B got sections of its own the page gained a second
     set of chip fields, and this test — which had counted every chip on the page
     — failed. It was right to: **axis B chips deliberately repeat**, because a
     record carries several tags or none. Counting both sets together would have
     asserted that tags partition the register, which is the one thing the page
     spends a standfirst warning against. */
  const { rendered, snap } = boot();
  const all = [];
  for (const k of BUCKET_ORDER) {
    const body = sectionBody(rendered, snap.buckets.names[k]);
    all.push(...chipSlugs(body));
  }
  assert.equal(all.length, snap.records.active,
    "the seven axis-A chip fields should hold every active record");
  assert.equal(new Set(all).size, all.length,
    "a record appears in two bucket sections — axis A is not a partition");
});

test("axis B is drawn as tags and never as a partition", () => {
  /* The counts total more than the register and 35 records carry nothing, so a
     tag section must not print a share and must not look like the seven states. */
  const { rendered, snap } = boot();
  const B = snap.buckets;
  const tagTotal = Object.values(B.b).reduce((a, b) => a + b, 0);
  assert.ok(tagTotal > snap.records.active);
  for (const [t, n] of Object.entries(B.b)) {
    const body = sectionBody(rendered, B.names[t]);
    const chips = chipSlugs(body);
    assert.equal(chips.length, n, `${t}: heading count and names printed disagree`);
    assert.deepEqual(chips.slice().sort(),
      here(Object.entries(B.members).filter(([, v]) => (v.b || []).includes(t))
        .map(([s]) => s)).sort(),
      `${t}: chips disagree with the snapshot's membership`);
    assert.match(body, /class="bk tagsec"/, `${t} must be drawn as a tag section`);
    assert.ok(!/% of the register/.test(body),
      `${t} prints a share — tags divide nothing and a percentage implies a whole`);
  }
});

test("a bucket's rule is rendered from the snapshot, never written into the page", () => {
  /* Same rule banner.js exists for: three hand-written copies of one paragraph
     drifted, and the stale one claimed `mondo:` was unresolved on every record
     long after 121 of 140 were resolved. A definition printed on a public page
     is exactly that shape of text. */
  const { html, rendered, snap } = boot();
  // Compare as TEXT. `**bold**` becomes <b>, `code` becomes <code>, so a raw
  // substring match against the HTML fails on any rule with markup inside it —
  // which is most of them, and is a fact about the assertion rather than about
  // the page.
  const text = s => s.replace(/<[^>]*>/g, "")
    .replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/\s+/g, " ").trim();
  const flat = text(rendered);
  for (const k of BUCKET_ORDER) {
    const rule = snap.buckets.defs[k].rule;
    assert.ok(rule && rule.length > 20, `${k} has no rule in the snapshot`);
    const plain = rule.replace(/[*`]/g, "").replace(/\s+/g, " ").trim();
    assert.ok(flat.includes(plain),
      `${k}: the rule from buckets.yaml is not rendered on the page`);
    assert.ok(!text(html).includes(plain.slice(0, 40)),
      `${k}: the page carries its own copy of the rule — it must come from the snapshot`);
  }
});

test("the year-over-year diff is computed at build time, not in the page", () => {
  /* The comparison has three refusals in it — missing membership, a changed
     rule digest, and following records by permanent id rather than slug. A
     second implementation in JavaScript is how this page would eventually
     report eight new records as eight diseases improving. */
  const { html, sandbox } = boot();
  assert.ok(Array.isArray(sandbox.window.NORDSTERN_BUCKET_DIFFS),
    "snapshots.js must publish the build-time diffs");
  assert.match(html, /NORDSTERN_BUCKET_DIFFS/,
    "the page must read the generated diff");
  // The page may READ arrivals/movements; it must not derive them by comparing
  // two snapshots itself.
  assert.ok(!/SNAPS\s*\[\s*SNAPS\.length\s*-\s*2\s*\]/.test(html),
    "the page appears to compare two snapshots itself — that derivation is check.py's");
});

test("with no comparable prior snapshot, the page says so instead of implying one", () => {
  const { rendered, sandbox } = boot();
  const d = sandbox.window.NORDSTERN_BUCKET_DIFFS.at(-1);
  if (!d || d.skipped) {
    assert.match(rendered, /No comparison\s+yet/,
      "a page with nothing to compare must say so");
    assert.ok(!/\bdiseases? changed state\b/.test(rendered),
      "must not print a change figure it cannot compute");
  } else {
    assert.match(rendered, /changed state/,
      "a comparable pair should render the movement line");
  }
});

test("a record is findable by the name a person would search for", () => {
  /* WHY THIS TEST EXISTS, AND WHY IT CHANGED ONCE.
     The dashboard listed `refractive-error` under *it works and it does not
     arrive* and **the word "glasses" appeared nowhere on the page**. Slugs are
     the register's handles, not anybody's vocabulary.

     The first fix put the whole `also` list in a clipped span so browser find
     would reach it. That was WORSE than not fixing it: ctrl-F matched, scrolled,
     and highlighted nothing visible — a page that looks broken. **Text search
     can find and a reader cannot see is not findability**, so this now asserts
     the plain name is in VIEW and that nothing on the page is visually clipped
     to fake a match. */
  const { html, rendered, slim } = boot();
  const withCommon = here(slim.filter(r => r.common));
  assert.ok(withCommon.length > 15,
    "slim.js should carry `common` — run check.py --build");

  assert.ok(!/clip\s*:\s*rect/.test(html),
    "something on this page is visually clipped; if it is there for browser " +
    "find, it is a false match a reader cannot see");

  const missing = here(withCommon
    .filter(r => !rendered.includes(`<span class="common">${r.common}</span>`))
    .map(r => r.slug));
  assert.deepEqual(missing, [],
    "records whose ordinary name is not rendered:\n" + missing.join("\n"));

  // the specific case that prompted all of it
  assert.match(rendered, /<span class="common">glasses<\/span>/,
    "somebody looking for glasses must see the word, not just match it");
  assert.match(rendered, /<span class="common">sleeping sickness<\/span>/);
});

test("chip fields are not ordered by deaths", () => {
  /* THE BIAS THIS PAGE EXISTS TO CORRECT, REINTRODUCED IN THE PRESENTATION
     LAYER. Sorting by mortality put the largest access failure in the world at
     the bottom of the section about access failures, because glasses kill
     nobody. Alphabetical is the neutral order and this asserts it. */
  const { rendered, snap, slim } = boot();
  const bySlug = Object.fromEntries(slim.map(r => [r.slug, r]));
  for (const k of BUCKET_ORDER) {
    const names = chipSlugs(sectionBody(rendered, snap.buckets.names[k]))
      .map(s => bySlug[s].name || s);
    assert.deepEqual(names, names.slice().sort((a, b) => a.localeCompare(b)),
      `${k}: chips are not in alphabetical order`);
  }
});

test("a bucket's exemplars come from buckets.yaml and are members of it", () => {
  /* The exemplars exist because alphabetical membership hides things — the
     largest unmet need in the register is called *Uncorrected refractive error*
     and sorts 66th of 68. They are a stated editorial choice, so they must come
     from the definitions file rather than the page, and they must actually be in
     the bucket they illustrate or the section is lying about its own contents. */
  const { html, rendered, snap } = boot();
  const defs = snap.buckets.defs;
  let shown = 0;
  for (const [slug, def] of Object.entries(defs)) {
    const ex = here(def.examples);
    if (!ex.length) continue;
    const body = sectionBody(rendered, snap.buckets.names[slug]);
    const drawn = [...body.matchAll(/<a class="chip ex" data-slug="([a-z0-9-]+)"/g)]
      .map(m => m[1]);
    assert.deepEqual(drawn, ex, `${slug}: exemplars drawn do not match buckets.yaml`);
    shown += drawn.length;
    // and each must belong to the thing it illustrates
    for (const e of drawn) {
      const m = snap.buckets.members[e];
      assert.ok(m, `${slug} names ${e} as an example and no such record exists`);
      const inIt = m.a === slug || (m.b || []).includes(slug);
      assert.ok(inIt, `${slug} names ${e} as an example, but ${e} is not in it`);
    }
    assert.ok(!html.includes(ex.join(", ")),
      `${slug}: the page carries its own copy of the examples`);
  }
  assert.ok(shown > 20, "expected exemplars on most sections");
});
